version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.6
    environment:
      AIRFLOW_HOME: ./airflow
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache: pipfile-lock-{{ checksum "Pipfile.lock" }}
      - run:
          name: install pipenv
          command: pip install pipenv --upgrade
      - run:
          name: install deps from lockfile
          command: pipenv install --dev --deploy
      - run:
          name: Run tests
          command: pipenv run python -m pytest tests
      - save_cache:
          key: pipfile-lock-{{ checksum "Pipfile.lock" }}
          paths: .venv

workflows:
  main:
    jobs:
      - build-and-test
