version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.6
    environment:
      AIRFLOW_HOME: ./airflow
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-
      - run:
          name: install pipenv
          command: pip install pipenv --upgrade
      - run:
          name: install deps from lockfile
          command: pipenv install --dev --deploy
      - run:
          name: check formatting
          command: pipenv run black --check .
      - run:
          name: run linter
          command: pipenv run pylint --rcfile=.pylintrc dags
      - run:
          name: Run tests
          command: pipenv run python -m pytest tests
      - save_cache:
          paths:
            - .venv
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

workflows:
  main:
    jobs:
      - build-and-test
